<?php

namespace App\Tests\Unit\Search\Decorator;

use App\Search\Client\ApiConferenceSearch;
use App\Search\Decorator\CacheableConferenceSearch;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Contracts\Cache\CacheInterface;
use Throwable;
use function Symfony\Component\String\u;

class CacheableConferenceSearchTest extends TestCase
{
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function assertPreConditions(): void
    {
        parent::assertPreConditions(); // TODO: Change the autogenerated stub
    }

    #[Test]
    public function cacheReturnsDataWhenHit(): void
    {
        $search = new CacheableConferenceSearch(...$this->getMocks());
        $result = $search->searchByName('hit');

        $this->assertSame('from cache', $result['conferences']);
    }

    #[Test]
    public function cacheReturnsCallToInnerWhenMiss(): void
    {
        $search = new CacheableConferenceSearch(...$this->getMocks(false));
        $result = $search->searchByName('miss');

        $this->assertSame('from client', $result['conferences']);
    }

    protected function onNotSuccessfulTest(Throwable $t): never
    {
        parent::onNotSuccessfulTest($t); // TODO: Change the autogenerated stub
    }

    protected function assertPostConditions(): void
    {
        parent::assertPostConditions(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }

    private function getMocks(bool $hit = true): array
    {
        $client = $this->createMock(ApiConferenceSearch::class);
        $client
            ->expects($hit ? $this->never() : $this->once())
            ->method('searchByName');
        $cache = $this->createMock(CacheInterface::class);
        $cache
            ->method('get')
            ->willReturnCallback(function ($key) use ($client) {
                    if ('hit' === $key) {
                        return ['conferences' => 'from cache'];
                    }

                    $client->searchByName('miss');

                    return ['conferences' => 'from client'];
            });
        $slugger = $this->createMock(SluggerInterface::class);
        $slugger
            ->method('slug')
            ->willReturnCallback(fn ($string) => u($string));

        return [$client, $cache, $slugger];
    }
}
